- name: create user roboshop
  hosts: localhost
  tasks:
   - name: check user exists or not (roboshop)
     ansible.builtin.command: id roboshop
     register: output 
     ignore_errors: true

   - name: print the command output   
     ansible.builtin.debug:
       msg: "output is: {{output}}" 
   - name: print output status 
     ansible.builtin.debug:
       msg: "{{output.rc}}"