- name: installing packags
  host: localhost
  become: yes
  tasks:
   - name: install package
     ansible.builtin.debug:
       name: "{{item}}"
       state: installed 
     loop:
     - nginx
     - postmap
