- name: installing packags
  host: webservers
  become: yes
  tasks:
   - name: install package
     ansible.builtin.debug:
       name: {{item}}
       state: installed 
     loop:
     - nginx
     - postmap
